### ISSUE TITLE
Should the role support enable_installer in config.php?

### ISSUE THREAD

**Issue by neidiom** [systemli/ansible-role-roundcube#31]
I am at `/installer/?_step=1` ang getting this message

```
The installer is disabled!
To enable it again, set $config['enable_installer'] = true; in RCUBE_CONFIG_DIR/config.inc.php
```
Should the role support enable_installer in config.php?

**Comment by neidiom** [comment]
Related to https://github.com/systemli/ansible-role-roundcube/issues/35

**Comment by t2d** [comment]
We also didn't install roundcube with this role, but imported our prior setup. However, I would accept a PR implementing this, if it comes with a secure default.
